name: Lint Commit Messages
on: [pull_request, push]

jobs:
  commitlint:
    runs-on: [self-hosted, cdorunner-4p-kernel-small]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
